### ISSUE TITLE
(De)Serialization issue

### ISSUE THREAD

**Issue by hussein-aitlahcen** [ConsenSys/gnark#615] opened 2023-04-01 12:43 UTC
Hi,

I'm facing a strange issue when committing a groth16 circuit and the vk/pk on disk then reloading and proving.

Here is the log when compiling the circuit, generating the vk/pk, dumping them to disk and proving directy:
```
14:26:38 INF building constraint builder nbConstraints=5148218
Setup PK/VK
Saving r1cs.bin
Saved 1824354025 bytes
Saving pk.bin
Saved 1187696506 bytes
Saving vk.bin
Saved 612 bytes
24514563
6076941
13
3
9
Proving...
14:29:14 DBG constraint system solver done backend=groth16 nbConstraints=5148218 took=1440.891508
14:29:20 DBG prover done backend=groth16 curve=bn254 nbConstraints=5148218 took=5673.178789
Proof: 0x13c16ce0332d62129026434b5f1fcb452278ef3bed4c6724c0b222b45e7c15c9183af55258bb83a7db3f0b265f4f2170a762b49df379ce1739dc33b30b93119e1a9d50e768d4696e7507c51a19485704ad3066a518863fadc25b254fb10fce502b0eb302521d4732d9925015adc2aef850399d24e9606c7fba255beebd52d3a20d10e2ea20afb4e735e01b0fbf1ab1b2561dad9c46a8631138a92c27bf183630228cbdc2ba5f2f6f5a4c272d271cb2bea7c6e3295346ffafef8ffb5a5c28f3982ae620292dd0cdc990ecc61565abf2b4e8fa2fbd92b1f9aa64c731406bf817181795d6e1994b54fdc05eebcebed8d0c5df3d55d6d70acbda1a5064f67e2827af
Extracting public
PublicWitness: 0x0000000800000000000000080000000000000000000000000000000064a9b313946ebb758fdaf98f60d3265000000000000000000000000000000000be961a320aad2833bb4e39e873fa6fd90000000000000000000000000000000064a9b313946ebb758fdaf98f60d3265000000000000000000000000000000000be961a320aad2833bb4e39e873fa6fd904ba75526359c27d85d689da12a4735fd83e99df6a1f6b8765b73ea27dbf7a9c2db5507df523efa29f5877f396e53e5b6fe9549ebbb5e20400db7c2c624f0a481dfbcc7c76bbd7f4e3415e1204b4424bd896541c02d0730862f5be8ee63023d8275c08c3dc199780268cc5e0488473e3d0a71fd5f43c63757ffe246ed9466c98
Verifying...
14:29:20 DBG verifier done backend=groth16 curve=bn254 took=1.003448
```

Here is the log when I try to load `r1cs.bin`, `vk.bin` and `pk.bin` (deserialization is successful) then prove:

```
Setup PK
Setup VK
24514563
6076941
13
3
9
Proving...
14:58:47 ERR error="unsatisfied constraint" backend=groth16 id=2917646 nbConstraints=5148218
panic: constraint #2917646 is not satisfied: [div] 311964/0 == <unsolved>
r1cs.(*builder).DivUnchecked
        api.go:257
rangecheck.(*commitChecker).commit.func2
        rangecheck_commit.go:99
```

How I am currently dumping the circuit:
```go
	r1csInstance := backend.NewCS(ecc.BN254)
	pk := backend.NewProvingKey(ecc.BN254)
	vk := backend.NewVerifyingKey(ecc.BN254)

       	var circuit lcgadget.Circuit

	fmt.Println("Compiling circuit...")
	r1csInstance, err = frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &circuit, frontend.WithCompressThreshold(300))
	if err != nil {
		panic(err)
	}

	fmt.Println("Setup PK/VK")
	pk, vk, err = backend.Setup(r1csInstance)
	if err != nil {
		panic(err)
	}

	saveTo := func(file string, x io.WriterTo) {
		fmt.Printf("Saving %s\n", file)
		f, err := os.Create(file)
		if err != nil {
			panic(err)
		}
		defer f.Close()
		w := bufio.NewWriter(f)
		written, err := x.WriteTo(w)
		if err != nil {
			panic(err)
		}
		fmt.Printf("Saved %d bytes\n", written)
		w.Flush()

	}

	saveTo("r1cs.bin", r1csInstance)
	saveTo("pk.bin", pk)
	saveTo("vk.bin", vk)

	fmt.Println(pk.NbG1())
	fmt.Println(pk.NbG2())
	fmt.Println(vk.NbG1())
	fmt.Println(vk.NbG2())
	fmt.Println(vk.NbPublicWitness())
```

How I am reloading the circuit:
```go
	r1csInstance := backend.NewCS(ecc.BN254)
	pk := backend.NewProvingKey(ecc.BN254)
	vk := backend.NewVerifyingKey(ecc.BN254)

	readFrom := func(file string) *os.File {
		f, err := os.OpenFile(file, os.O_RDONLY, os.ModePerm)
		if err != nil {
			panic(err)
		}
		return f
	}

	r1csBin := readFrom("r1cs.bin")
	_, err = r1csInstance.ReadFrom(r1csBin)
	if err != nil {
		panic(err)
	}
	r1csBin.Close()

	fmt.Println("Setup PK")
	pkBin := readFrom("pk.bin")
	_, err = pk.ReadFrom(pkBin)
	if err != nil {
		panic(err)
	}
	pkBin.Close()

	fmt.Println("Setup VK")
	vkBin := readFrom("vk.bin")
	_, err = vk.ReadFrom(vkBin)
	if err != nil {
		panic(err)
	}
	vkBin.Close()

	fmt.Println(pk.NbG1())
	fmt.Println(pk.NbG2())
	fmt.Println(vk.NbG1())
	fmt.Println(vk.NbG2())
	fmt.Println(vk.NbPublicWitness())
```

Am I doing something completely wrong? Worth to note, the `(vk|pk).Nb(G1|G2|PublicWitness)` are equal when compiling and reloading. I'm also not facing any error while deserializing

**Comment by ivokub** [comment] 2023-04-03 08:49
Thanks for reporting. This is a duplicate of #580, but haven't been able to fix yet. If you want to fix locally then need to marshal commitment info in https://github.com/ConsenSys/gnark/blob/develop/backend/groth16/bn254/marshal.go#L95 and unmarshal in https://github.com/ConsenSys/gnark/blob/develop/backend/groth16/bn254/marshal.go#L145 (correspondingly for other curves).

Proper fix would take a bit more though - we include some redundant commitment info in the verification key struct. That's why haven't fixed properly yet, but will soon.

**Closed by ivokub** 2023-04-03 08:49 UTC

**Comment by hussein-aitlahcen** [comment] 2023-04-19 08:08
Thanks a lot, I will apply a local fix for the time being
