### ISSUE TITLE
bug: required root of unity doesn't exist

### ISSUE THREAD

**Issue by gbotrel** [Consensys/gnark#611] opened 2023-03-30 20:00 UTC
```
--- FAIL: TestProver/bw6_633 (138.65s)
[12533](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12534)
panic: m (1600008) is too big: the required root of unity does not exist [recovered]
[12534](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12535)
	panic: m (1600008) is too big: the required root of unity does not exist
[12535](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12536)

[12536](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12537)
goroutine 4861 [running]:
[12537](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12538)
testing.tRunner.func1.2({0x90d100, 0xc000166010})
[12538](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12539)
	/opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1526 +0x24e
[12539](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12540)
testing.tRunner.func1()
[12540](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12541)
	/opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1529 +0x39f
[12541](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12542)
panic({0x90d100, 0xc000166010})
[12542](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12543)
	/opt/hostedtoolcache/go/1.20.2/x64/src/runtime/panic.go:884 +0x213
[12543](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12544)
github.com/consensys/gnark-crypto/ecc/bw6-633/fr/fft.NewDomain(0x186a08, {0x0, 0x0, 0x981360?})
[12544](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12545)
	/home/runner/go/pkg/mod/github.com/consensys/gnark-crypto@v0.9.2-0.20230329155745-a57dcc3b53de/ecc/bw6-633/fr/fft/domain.go:85 +0x2d7
[12545](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12546)
github.com/consensys/gnark/backend/plonk/bw6-633.(*ProvingKey).initDomains(0xc0000a8380, 0xc000108ea0?)
[12546](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12547)
	/home/runner/work/gnark/gnark/backend/plonk/bw6-633/setup.go:343 +0xfe
[12547](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12548)
github.com/consensys/gnark/backend/plonk/bw6-633.Setup(0xc0001b8000, 0xc00203e000)
[12548](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12549)
	/home/runner/work/gnark/gnark/backend/plonk/bw6-633/setup.go:129 +0xf7
[12549](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12550)
github.com/consensys/gnark/backend/plonk.Setup({0xa78c78?, 0xc0001b8000?}, {0xa73968?, 0xc00203e000?})
[12550](https://github.com/ConsenSys/gnark/actions/runs/4568192454/jobs/8062965454#step:6:12551)
	/home/runner/work/gnark/gnark/backend/plonk/plonk.go:113 +0x265
```

This is triggered on develop because I accidentally pushed  a reference circuit of 400K constraints (instead of 40k before I think). 

I will fix the size of the reference circuit, but... something is odd nonetheless :)

**Comment by sid-alluri** [comment] 2023-10-10 21:36
Hi @gbotrel @ThomasPiellard 
I am facing a similar issue, and my tests are passing with assert.ProverSucceeded. However, they are failing with the above error when I write the code with actual setup, prove, and verify functions. Is there any fix for this issue?

**Comment by gbotrel** [comment] 2023-10-10 21:41
If I recall, this was due to the low 2 adicity of these curves (cc @yelhousni ) : 
```
"bw6-633" --> const maxOrderRoot uint64 = 20
"bls24-315" --> const maxOrderRoot uint64 = 22
```

**Comment by yelhousni** [comment] 2023-10-10 21:45
> If I recall, this was due to the low 2 adicity of these curves (cc @yelhousni ) :
> 
> ```
> "bw6-633" --> const maxOrderRoot uint64 = 20
> "bls24-315" --> const maxOrderRoot uint64 = 22
> ```

yeah for a 400k PlonK circuit, I would assume bw6-633 would throw an error.

**Comment by sid-alluri** [comment] 2023-10-10 22:13
I was using BN254 in both assert.ProverSucceeded and actual prover, but the issue is only in the actual prover. I couldn't understand why. Also any limitations on # of constraints Gnark can handle across available curves?

**Comment by ivokub** [comment] 2023-10-10 23:10
Yes, the error should only be thrown when running the prover (more specifically, the Fast Fourier Transform (FFT) part of the prover). The maximum input size for FFT algorithm depends on the 2-adicity of the scalar field (see https://www.cryptologie.net/article/559/whats-two-adicity/).

It is defined:
* BN254 - 2**28
* BW6-633 - 2**20
* BLS23-315 - 2**22
* ... (grep for `maxOrderRoot` in gnark-crypto for the rest).

For Groth16, the input to the FFT has the same length as the number of constraints and for PLONK the input to FFT is 4 times the number of constraints. So for BW6-633 we can have maximally `(2**20)/4 = 256000` constraints.
You also see that it depends on the curve, some curves have very big 2-adicity, but they are otherwise not ideal (compatibilty, field operations speeds etc.).

**Comment by sid-alluri** [comment] 2023-10-11 17:15
Thank you very much for the explanation. It's really helpful

**Comment by ivokub** [comment] 2023-10-13 13:44
Added task #864 to make the errors more descriptive and check during compile-time.

**Closed by ivokub** 2023-10-13 13:44 UTC
Labels: bug
